### PR TITLE
New book tools

### PR DESCRIPTION
**Pull request by brittany-johnson**
After rearranging some of the organization of this repo, I think it will now make sense to newer employees. Please review each .md file as there are some 'Notes' that require action on my part if you approve of all the changes and suggestion.

### CODE REVIEW

**Comment by tx-ares** [comment]
@brittany-johnson Can you try to invite me to review again?

**Comment by philschatz** [comment]
Thanks for including the `**Note:**` comments! they will be great for discussion.

Also, I am not sure if this is useful but the raw HTML format is auto-documented at https://github.com/Connexions/cnxml/pull/9#issuecomment-309172457 (still need to get that PR merged)

**Comment by philschatz** [comment]
Removing myself because we discussed the `**Note:**` items in meeting. Pleas re-request me for review when ready for me to take another look 😄

**Review by philschatz — COMMENTED** [review]
Noted comments in the meeting

**Comment by philschatz** [comment]
Also, RE terms: This might be useful to pull from as well: https://docs.google.com/document/d/1lo10qn-Gy5j8KRiccXKbXPlNHWNfF_8Ub6EWP49UgG0/edit#

**Comment by brittany-johnson** [comment]
@philschatz @TxsAdamWest @helenemccarron Hey guys! A few changes have been made and everything should be okay to merge now. Please take a look when you get a chance. Thanks!

**Review by tx-ares — APPROVED** [review]
Looks pretty sweet.  Kudos for acronym page.  I actually learned a lot from that!  💯

**Pull request merged**
